# Generated by Django 4.2.4 on 2023-10-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fname',
            field=models.CharField(max_length=20),
        ),
    ]
